version: "3.8"
services:
  db:
    image: postgres:14
    container_name: doctor_report_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  backend:
    build: ./backend
    container_name: doctor_report_backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
      
  frontend:
    build: ./frontend
    container_name: doctor_report_frontend
    ports:
      - "3000:3000"

volumes:
  db_data:
