name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io -q

      - name: Build and push Docker images
        run: |
          # Build and push backend
          cd backend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-backend:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-backend:${{ github.sha }}
          
          # Build and push frontend
          cd ../frontend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-frontend:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-frontend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          # Deploy backend
          gcloud run deploy doctor-report-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-backend:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet

          # Deploy frontend
          gcloud run deploy doctor-report-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-frontend:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet

      - name: Clean up
        if: always()
        run: |
          gcloud container images delete gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-backend:${{ github.sha }} --quiet || true
          gcloud container images delete gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-report-frontend:${{ github.sha }} --quiet || true
